### ISSUE TITLE
Modules listed in transpilers should implicitly be allowUnsued

### ISSUE THREAD

**Issue by alexdavid** [charlierudolph/dependency-lint#18]
If I am building my project in a compile-to-js language, I'm probably going to want that package as a devDependency for my build script, but I'm most likely not going to be requiring it anywhere in my project.

I think dependency lint should automatically include any modules listed under transpilers in the `allowUnused` section.

Thoughts?

**Comment by charlierudolph** [comment]
I'd be fine with that. The build script should allow dependency-lint to see its use, but this sounds correct in the case that the user hasn't added a build script yet.

**Comment by alexdavid** [comment]
Yeah, that's a good point. This mostly came about from @kevgo's new convention of not using npm's `scripts` block, but instead using shell scripts in `bin/`

**Comment by charlierudolph** [comment]
For shell scripts, dependency lint could just search for the executable in the file. Could be new options `shellScriptPatterns` and `devShellScriptPatterns`.

**Comment by kevgo** [comment]
+1 on `shellScriptPatterns`

**Comment by charlierudolph** [comment]
Added in the ability to search shell scripts for module executables. Since that lack was the original reason for this request, can you try that out and see if this is still needed?

**Comment by charlierudolph** [comment]
@alexdavid any thoughts on my previous comment?

**Comment by alexdavid** [comment]
I haven't had a chance to try this out yet since I've been using package.json scripts. @kevgo uses shell scripts though. Have you had a chance to try this out Kevin?

**Comment by kevgo** [comment]
That seems to work well. Thanks!

**Comment by charlierudolph** [comment]
Closing this out as it appears to be resolved. Please reopen if you want to discuss more
