### ISSUE TITLE
Incorrectly assumes missing "rc" dependency

### ISSUE THREAD

**Issue by kevgo** [charlierudolph/dependency-lint#32]
My project has "rc" as a dependency, which exports an "rc" binary. Dependency-lint finds "rc" in many of my scripts, wrongfully assuming "rc" is used. The regex dependency-lint uses to find occurrences of binaries should wrap the binary name in word boundaries (`\b`) to make this search more robust.

**Comment by charlierudolph** [comment]
Fix release in 4.1.1
