### ISSUE TITLE
Which Node and NPM versions does this library run on?

### ISSUE THREAD

**Issue by kevgo** [charlierudolph/dependency-lint#34]
I'm getting errors on Node 4. Possibly because older NPM version? This should be documented and regularly tested against via Travis CI. 

Adding Travis:
- log in to https://travis-ci.org
- go to your user profile and activate monitoring this repo
- add a file `.travis.yml` ([working example](https://github.com/Originate/tertestrial-server/blob/master/.travis.yml)) to the code base

**Comment by charlierudolph** [comment]
Sounds good. Was thinking about adding this anyway as I want to merge in my generators code and was debating whether or not to support older versions (though an additional transpiler).

**Comment by kevgo** [comment]
Node 4 is only one year old, since they release new major versions every 6 months. I think supporting at least this version makes sense, since many Linux distros are stuck with such old versions.

**Comment by charlierudolph** [comment]
Just set up travis and all is passing on node 4. Can you please give more detail about the error you are running into?

**Comment by kevgo** [comment]
It works for me too now. I swear I was getting persistent Node4 specific errors, even when repeating the build. Should have posted a screenshot. Cannot reproduce them anymore, sorry for the false alarm. It's good to check utilitarian NPM modules like dependency-lint against different runtime versions anyways, and document it. So something good came out of this.
