### ISSUE TITLE
add option quite in CLI

### ISSUE THREAD

**Issue by alexander-akait** [charlierudolph/dependency-lint#45]
I would like to have a possible output only when there are errors, i can do PR for this if accepted

**Comment by charlierudolph** [comment]
I've been meaning to do something like this. Yeah it would be great if you'd like to implement this.

**Comment by alexander-akait** [comment]
@charlierudolph How about not output by default and add `-v --verbose` option to enable output. It is default behavior for most cli command.

**Comment by charlierudolph** [comment]
Sounds good to me
